In [9]:
import pandas as pd

In [11]:
bucket='sarima/data'
data_key= 'MDA_dataframeArthur.csv'
data_location='s3://{}/{}'.format(bucket, data_key)

data=pd.read_csv(data_location)

In [12]:
data

,result_timestamp,laeq,hour,day,day_of_month,month,weekend,LC_HUMIDITY,LC_DWPTEMP,LC_n,LC_RAD,LC_RAININ,LC_DAILYRAIN,LC_WINDDIR,LC_WINDSPEED,LC_RAD60,LC_TEMP_QCL0,LC_TEMP_QCL1,LC_TEMP_QCL2,LC_TEMP_QCL3
0,2022-01-02 00:10:00,40.954667,0,6,2,1,1,91.0,11.88,38.0,0.0,0.000,0.000,-48.0,0.04,0.0,13.28,13.28,13.223,13.23639
1,2022-01-02 00:20:00,37.623667,0,6,2,1,1,90.0,11.72,37.0,0.0,0.000,0.000,45.0,0.02,0.0,13.28,13.28,13.223,13.16699
2,2022-01-02 00:30:00,36.445333,0,6,2,1,1,90.0,11.72,38.0,0.0,0.000,0.000,-52.0,0.04,0.0,13.28,13.28,13.223,13.19886
3,2022-01-02 00:40:00,38.298000,0,6,2,1,1,90.0,11.72,37.0,0.0,0.000,0.000,34.0,0.02,0.0,13.28,13.28,13.223,13.16699
4,2022-01-02 00:50:00,39.350417,0,6,2,1,1,90.0,11.72,38.0,0.0,0.000,0.000,0.0,0.00,0.0,13.28,13.28,13.223,13.09212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52266,2022-12-31 23:10:00,52.203333,23,5,31,12,1,94.0,12.63,38.0,0.0,0.000,0.007,28.0,0.09,0.0,13.51,13.51,13.453,13.48489
52267,2022-12-31 23:20:00,54.622833,23,5,31,12,1,94.0,12.61,37.0,0.0,0.000,0.000,72.0,0.03,0.0,13.50,13.50,13.443,13.40492
52268,2022-12-31 23:30:00,56.135667,23,5,31,12,1,94.0,12.67,38.0,0.0,0.000,0.000,63.0,0.04,0.0,13.56,13.56,13.503,13.47255
52269,2022-12-31 23:40:00,59.380333,23,5,31,12,1,94.0,12.73,37.0,0.0,0.003,0.000,34.0,0.14,0.0,13.61,13.61,13.553,13.60671
52270,2022-12-31 23:50:00,57.698331,23,5,31,12,1,95.0,12.78,38.0,0.0,0.000,0.000,-167.0,0.02,0.0,13.61,13.61,13.553,13.51775